name: Test the GitHub Action

on: [push]

jobs:
  test-action:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Action
        uses: ./
        id: run-action
